---
title: "CEIGRAS"
format: html
---

# Letrero WAGNER - LALANGUI

```{r}
library(huito)
library(dplyr)
library(googlesheets4)
source('https://inkaverse.com/setup.r')
```

```{r}
# Cargar los datos desde Google Sheets

url <- "https://docs.google.com/spreadsheets/d/1wruOysAqRKvsWfm0AI0NINHRfSaNwC_ZDoEhJT_2jBo/edit?pli=1&gid=1673111549#gid=1673111549"

gs <- url %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read("cartel")
# Frijol_Lonya Chico_Wagner 

# Definir la fuente
font <- c("Anton", "Anton", "Anton") 
huito_fonts(font)
```

```{r}
## Capaz

label1 <- fb %>% 
  label_layout(
    size = c(120, 80),  # Dimensiones del cartel (ancho x alto)
    border_color = "black"
  ) %>%
  include_image(value = "D:/Practicas_2026/labels/frijol-2.jpg"
                , size = c(37, 25)
                , position = c(102, 12)
                , opts = "image_scale(700)"
  ) %>%
  
  include_image(value = "https://www.shutterstock.com/image-photo/beans-isolated-on-white-background-600nw-2521916411.jpg"
                , size = c(35, 50)
                , position = c(75, 10)
                , opts = "image_scale(500)"
  ) %>%
  # Incluir los logos 
  
  # Agregar el logo CEIGRAS
  include_image(
    value = "D:/Practicas_2026/labels/logo_CEIGRAS.jpeg",
    size = c(35, 35),  # Incrementar tamaño del logo
    position = c(63, 70)
  ) %>%
  include_image(
    value = "https://www.peruconciencia.pe/wp-content/uploads/24.-Universidad-Nacional-Toribio-Rodriguez-de-Mendoza-de-Amazonas-UNTRM.jpg",
    size = c(40, 30),  # Incrementar tamaño del logo
    position = c(20, 70)
  ) %>% 
  include_image(
    value = "D:/Practicas_2026/labels/INDES-CES logo.jpg",
    size = c(30, 30),  # Incrementar tamaño del logo
    position = c(104, 72)
  ) %>% 
  include_text(
    value = " MEJORAMIENTO DEL SERVICIO DE PROMOCIÓN DE LA CIENCIA, TECNOLOGÍA E INNOVACIÓN TECNOLÓGICA\n\nEN EL CENTRO DE INVESTIGACIÓN E INNOVACIÓN EN GRANOS Y SEMILLAS CEIGRAS DE LA UNTRM\n\nDISTRITO DE LAMUD, PROVINCIA DE LUYA, REGION DE AMAZONAS\n\n CUI: 2590588 - (CEIGRAS) "
   ,position = c(60, 50),
    size = 90,# Incrementar tamaño del texto
    color = "#003d08",  # Cambiar a un color más visible
    font = font[1]
  ) %>% 
 include_text(
  value ="Banco de Germoplasma de frijoles (Phaseolus spp.) de la región Amazonas",  
  position = c(60, 32),
  size = 95,  
  color = "#582900",
  font = font[1]
) %>% 
  include_text(
    value = " Ubicación:", 
    position = c(8,26),
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[3]
    , opts = "hjust = 0"
  ) %>% 
  include_text(
    value = " Lonya Chico, Luya, Amazonas ( 6°13′46.07″S - 77°57′20.20″W )", 
    position = c(20.5,26),
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[3]
    , opts = "hjust = 0"
  ) %>% 
  include_text(
    value = " Tesista:",
    position = c(8,20),
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[3]
    , opts = "hjust = 0"
  ) %>% 
  
  include_text(
    value = "Jefferson Ivan Lalangui Peña",
    position = c(18,20),
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[3]
    , opts = "hjust = 0"
  ) %>% 
  
    include_text(
    value = " Encargado:",
    position = c(8,14),
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[3]
    , opts = "hjust = 0"
  ) %>% 
  include_text(
    value = "  Wagner Meza Maicelo",
    position = c(21,14),
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[3]
    , opts = "hjust = 0"
  ) %>% 
  
  include_text(
    value = " Coordinador:" ,
    position = c(8,8),
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[3]
    , opts = "hjust = 0"
  ) %>% 
  
  include_text(
    value = " Flavio Lozano Isla" ,
    position = c(23,8),
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[3]
    , opts = "hjust = 0"
  )

# Visualización previa
label1 %>% 
  label_print(mode = "preview", viewer = T)




```

```{r}
# Descargar 
label1 %>%
  label_print(mode = "c",
               paper = c(125, 85),
               nlabels = 1,  # Solo una etiqueta
               filename = "D:/Practicas_2026/labels/Letrero_WAGNER-LALANGUI")
```

# Letrero VICTOR - HERMES

```{r}
library(huito)
library(dplyr)
library(googlesheets4)
source('https://inkaverse.com/setup.r')
```

```{r}
# Cargar los datos desde Google Sheets

url <- "https://docs.google.com/spreadsheets/d/1wruOysAqRKvsWfm0AI0NINHRfSaNwC_ZDoEhJT_2jBo/edit?pli=1&gid=1673111549#gid=1673111549"

gs <- url %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read("cartel")
# Frijol_Lonya Chico_Wagner 

#> Google fonts: https://fonts.google.com/

# Definir la fuente
font <- c("Anton", "Barlow Condensed") 
huito_fonts(font)
```

```{r}
## Capaz

labelVH <- fb %>% 
  label_layout(
    size = c(120, 80),  # Dimensiones del cartel (ancho x alto)
    border_color = "black"
  )  %>%
  include_image(value = "Quinua-4.jpg"
                , size = c(37, 25)
                , position = c(102, 12)
                , opts = "image_scale(700)"
  ) %>%
  # Incluir los logos 
  
  # Agregar el logo CEIGRAS
  include_image(
    value = "D:/Practicas_2026/labels/logo_CEIGRAS.jpeg",
    size = c(35, 35),  # Incrementar tamaño del logo
    position = c(63, 73)
  ) %>%
  include_image(
    value = "https://www.peruconciencia.pe/wp-content/uploads/24.-Universidad-Nacional-Toribio-Rodriguez-de-Mendoza-de-Amazonas-UNTRM.jpg",
    size = c(40, 30),  # Incrementar tamaño del logo
    position = c(20, 73)
  ) %>% 
  include_image(
    value = "D:/Practicas_2026/labels/INDES-CES logo.jpg",
    size = c(30, 30),  # Incrementar tamaño del logo
    position = c(104, 74)
  ) %>% 
  include_text(
    value = " MEJORAMIENTO DEL SERVICIO DE PROMOCIÓN DE LA CIENCIA, TECNOLOGÍA E INNOVACIÓN TECNOLÓGICA\n\nEN EL CENTRO DE INVESTIGACIÓN E INNOVACIÓN EN GRANOS Y SEMILLAS CEIGRAS DE LA UNTRM\n\nDISTRITO DE LAMUD, PROVINCIA DE LUYA, DEPARTAMENTO DE AMAZONAS\n\n CUI: 2590588 - (CEIGRAS) "
   ,position = c(60, 52.5)
   ,fontface = "bold",
   size = 90,# Incrementar tamaño del texto
    color = "#003d08",  # Cambiar a un color más visible
    font = font[1]
  ) %>% 
include_text(
  value = "Evaluación agronómica de tres accesiones de quinua (",
  position = c(38.75, 36),
  size = 95,
  color = "#582900",
  font = font[1]
) %>%
include_text(
  value = "Chenopodium quinoa",
  position = c(91.75, 36),
  fontface = "bold.italic",
  size = 120,
  color = "#582900",
  font = font[2]
) %>%
include_text(
  value = "Willd.)",
  position = c(112.25, 36),
  size = 95,
  color = "#582900",
  font = font[1]
)  %>%
include_text(
  value = "asociadas con frijol (",
  position = c(17, 32),
  size = 95,
  color = "#582900",
  font = font[1]
)  %>%
include_text(
  value = "Phaseolus vulgaris",
  position = c(45.5, 32),
  fontface = "bold.italic",
  size = 120,
  color = "#582900",
  font = font[2]
) %>%
include_text(
  value = "L.) bajo dos distanciamientos de siembra    ",
  position = c(90, 32),
  size = 95,
  color = "#582900",
  font = font[1]
)  %>%
include_text(
  value = "en Lonya Chico, Luya, Amazonas",
  position = c(60, 28),
  size = 95,
  color = "#582900",
  font = font[1]
)%>% 
include_text(
    value = " Ubicación:", 
    position = c(8,23),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[1]
    , opts = "hjust = 0"
) %>% 
  include_text(
    value = " Lonya Chico, Luya, Amazonas (6°13′46.07″S - 77°57′20.20″W)",
    position = c(20.5,23),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[1]
    , opts = "hjust = 0"
) %>% 
  include_text(
    value = " Tesista:",
    position = c(8,17),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
  include_text(
    value = " Hermes Galoc Valqui",
    position = c(18,17),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
    include_text(
    value = " Encargado:",
    position = c(8,11),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
  include_text(
    value = "  Victor Hugo Baldera Chapoñan",
    position = c(21,11),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
  
  include_text(
    value = " Coordinador:" ,
    position = c(8,5),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
  
  include_text(
    value = " Flavio Lozano Isla" ,
    position = c(23,5),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[1]
    , opts = "hjust = 0"
  )
# Visualización previa
labelVH %>% 
  label_print(mode = "preview", viewer = T)

```

```{r}
# Descargar 
labelVH %>%
  label_print(mode = "c",
               paper = c(125, 85),
               nlabels = 1,  # Solo una etiqueta
               filename = "D:/Practicas_2026/labels/Letrero_VICTOR-HERMES")
```

# Letrero VICTOR - EDGAR

```{r}
library(huito)
library(dplyr)
library(googlesheets4)
source('https://inkaverse.com/setup.r')
```

```{r}
# Cargar los datos desde Google Sheets

url <- "https://docs.google.com/spreadsheets/d/1wruOysAqRKvsWfm0AI0NINHRfSaNwC_ZDoEhJT_2jBo/edit?pli=1&gid=1673111549#gid=1673111549"

gs <- url %>%
  as_sheets_id()

fb <- gs %>% 
  range_read("cartel")
# Frijol_Lonya Chico_Wagner 

#> Google fonts: https://fonts.google.com/

# Definir la fuente
font <- c("Anton", "Barlow Condensed") 
huito_fonts(font)
```

```{r}
## Capaz

labelVE <- fb %>% 
  label_layout(
    size = c(120, 80),  # Dimensiones del cartel (ancho x alto)
    border_color = "black"
  ) %>%
  include_image(value = "Quinua-4.jpg"
                , size = c(37, 25)
                , position = c(102, 12)
                , opts = "image_scale(700)"
  ) %>%
  # Incluir los logos 
  
  # Agregar el logo CEIGRAS
  include_image(
    value = "D:/Practicas_2026/labels/logo_CEIGRAS.jpeg",
    size = c(35, 35),  # Incrementar tamaño del logo
    position = c(63, 73)
  ) %>%
  include_image(
    value = "https://www.peruconciencia.pe/wp-content/uploads/24.-Universidad-Nacional-Toribio-Rodriguez-de-Mendoza-de-Amazonas-UNTRM.jpg",
    size = c(40, 30),  # Incrementar tamaño del logo
    position = c(20, 73)
  ) %>% 
  include_image(
    value = "D:/Practicas_2026/labels/INDES-CES logo.jpg",
    size = c(30, 30),  # Incrementar tamaño del logo
    position = c(104, 74)
  ) %>% 
  include_text(
    value = " MEJORAMIENTO DEL SERVICIO DE PROMOCIÓN DE LA CIENCIA, TECNOLOGÍA E INNOVACIÓN TECNOLÓGICA\n\nEN EL CENTRO DE INVESTIGACIÓN E INNOVACIÓN EN GRANOS Y SEMILLAS CEIGRAS DE LA UNTRM\n\nDISTRITO DE LAMUD, PROVINCIA DE LUYA, DEPARTAMENTO DE AMAZONAS\n\n CUI: 2590588 - (CEIGRAS) "
   ,position = c(60, 52.5)
   ,fontface = "bold",
   size = 90,# Incrementar tamaño del texto
    color = "#003d08",  # Cambiar a un color más visible
    font = font[1]
  ) %>% 
include_text(
  value = "Caracterización morfoagronómica de quinua (",
  position = c(40, 35),
  size = 95,
  color = "#582900",
  font = font[1]
) %>%
include_text(
  value = "Chenopodium quinoa",
  position = c(87, 35),
  fontface = "bold.italic",
  size = 120,
  color = "#582900",
  font = font[2]
) %>%
include_text(
  value = ") en",
  position = c(105.5,35),
  size = 95,
  color = "#582900",
  font = font[1]
)%>%
include_text(
  value = "Lamud, Luya, Amazonas",
  position = c(60, 31),
  size = 95,
  color = "#582900",
  font = font[1]
)%>%
include_text(
    value = " Ubicación:", 
    position = c(8,23),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[1]
    , opts = "hjust = 0"
) %>% 
  include_text(
    value = " Lonya Chico, Luya, Amazonas (6°13′46.07″S - 77°57′20.20″W)",
    position = c(20.5,23),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[1]
    , opts = "hjust = 0"
) %>% 
  include_text(
    value = " Tesista:",
    position = c(8,17),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
  include_text(
    value = " Edgar Orlando Campos Troyes",
    position = c(18,17),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
    include_text(
    value = " Encargado:",
    position = c(8,11),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
  include_text(
    value = "  Victor Hugo Baldera Chapoñan",
    position = c(21,11),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
  
  include_text(
    value = " Coordinador:" ,
    position = c(8,5),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#582900",
    font = font[1]
    , opts = "hjust = 0"
  ) %>% 
  include_text(
    value = " Flavio Lozano Isla" ,
    position = c(23,5),
    fontface = "bold",
    size = 80,  # Incrementar tamaño del texto
    color = "#003d08",
    font = font[1],
    opts = "hjust = 0"
    )
# Visualización previa
labelVE %>% 
  label_print(mode = "preview", viewer = T)

```

```{r}
# Descargar 
labelVE %>%
  label_print(mode = "c",
               paper = c(125, 85),
               nlabels = 1,  # Solo una etiqueta
               filename = "D:/Practicas_2026/labels/Letrero_VICTOR-EDGAR")
```
