---
title: "LOGO_CEIGRAS"
author: "CEIGRAS"
format: html
editor: visual
---

# Setup

```{r}
#| label: setup

source("https://inkaverse.com/setup.r")
```

## Field-book

```{r}
#> Google fonts: https://fonts.google.com/
# Vina Sans

# SIN FUENTES PARA EL LOGO
#font <- c("Vina Sans")
#huito_fonts(font)
```

## Labels

```{r}
 #colo azul: https://github.com/EOCT-234/Practicas_2026/blob/main/CEIGRAS_archivos/Logo_UNTRMpng.png
    #color blanco: https://raw.githubusercontent.com/EOCT-234/Practicas_2026/refs/heads/main/CEIGRAS_archivos/Logo_UNTRMpng_white.png

label <- label_layout(size = c(3.9, 0.6)
               , border_color = "white"
               , border_width = 0.1
               , background = "gray"
               ) %>%
  # Logo UNTRM
  include_image(
    value = "https://raw.githubusercontent.com/EOCT-234/Practicas_2026/refs/heads/main/CEIGRAS_archivos/Logo_UNTRMpng_white.png"
    , size = c(2,2)
    , position = c(1.05, 0.3)
    ) %>%  
  include_text(value = "CENTRO DE INVESTIGACIÓN"
               , position = c(3 , 0.4)
               , size = 3.5
               , color = "white"   #color de letras d euniversidad = #133E6B
               , fontface = "bold"
               ) %>% 
  include_text(value = "EN GRANOS Y SEMILLAS"
               , position = c(2.9 , 0.2)
               , size = 3.5
               , color = "white"
               , fontface = "bold"
               )

label %>% label_print()
```

```{r}
#| eval: false
label %>%
  label_print(
    mode = "c",
    paper = c(4, 0.7),
    filename = "ETIQUETA_UNTRM_white"
  )
```

```{r}
library(pdftools)
pdf_convert(
  "ETIQUETA_UNTRM_white.pdf",
  format = "png",
  dpi = 9000
)

```

```{r}
library(magick)

img <- image_read("logo_sin_fondo.png")

# convertir blanco en transparente
img_transp <- image_transparent(img, color = "none")
# image_blank( width = 400, height = 1200, color = "none")

image_write(img, "CEIGRAS_UNTRM_white_SF.png", density = 400)
```

```{r}
#Quitar fondo gris
img <- image_read("logo_sin_fondo.png")   # cambia por tu ruta si está en otra carpeta
img_transp <- image_transparent(img, "black", fuzz = 25)
#Quiar fondo/ falló
#img_transp <- image_transparent(
 # img,
  #color = "gray",   # gris del fondo aprox
  #fuzz = 20            # tolerancia (clave)
#)
image_write(img_transp, "logo_sin_fondo1.png", format = "png")
```

