---
title: "experimental labels"
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    self-contained: true
    output-file: "labels"
editor_options: 
  chunk_output_type: console
execute: 
  echo: true
  message: false
  warning: false
---

# Setup

```{r}
#| label: setup

source("https://inkaverse.com/setup.r")
```

## Field-book

```{r}
gs <- "https://docs.google.com/spreadsheets/d/1HzThbWZS16yzrJfLCan80wSNu8BGIuy6NETIqb0qHqQ/edit?gid=2124233866#gid=2124233866" %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read(ss = .,sheet = "fb")

#> Google fonts: https://fonts.google.com/

font <- c("Open Sans")
huito_fonts(font)
```

## Labels 

```{r}
label <- fb %>%
  label_layout(size = c(5.2, 3.5)
               , border_color = "blue"
               , border_width = 0.5
               ) %>%
  # Logo UNTRM
  include_image(
    value = "https://doctoradofisica.uni.edu.pe/wp-content/uploads/2024/01/d123d3.webp"
    , size = c(2.2,2.2)
    , position = c(1.15, 3.1)
    ) %>% 
  #Escala
  include_image(
    value = "https://huito.inkaverse.com/img/scale.pdf"
    , size = c(5, 1)
    , position = c(2.6 , 0.53)
    ) %>%
  #Logo CEIGRAS
  include_image(
    value = "D:/PRACTICAS-PREPROFESIONALES/Quinoa-osmotic-stress/experimento_quinua/Logo_CEIGRAS.jpeg"
    , size = c(1.6, 1.6)
    , position = c(3.2, 3.16)
    ) %>% 
  #QR
  include_barcode(
    value = "qrcode"
    , size = c(1.7, 1.7)
    , position = c(1.1, 1.95)
    ) %>%
  include_text(value = "plots"
               , position = c(4.6, 3.1)
               , size = 10
               , color = "black"
               , font= font[1]
               , fontface = "bold"
               ) %>% 
  include_text(value = "Accesión:"
               , position = c(2.8, 2.3)
               , size = 9
               , color = "black"
               , font = font[1]
               , fontface = "bold"
               ) %>%
  include_text(value = "Accesion"
               , position = c(4.6, 2.3)
               , size = 9
               , color = "black"
               , font = font[1]
               , fontface = "bold"
               ) %>% 
    include_text(value = "Temperatura:"
               , position = c(3.15,1.7)
               , size = 9
               , color = "black"
               , font = font[1]
               , fontface = "bold"
               )%>%
  include_text(value = "T°"
               , position = c(4.75,1.7)
               , size = 9
               , color = "black"
               , font = font[1]
               , fontface = "bold"
               )
label %>% label_print()
```

```{r}
#| eval: false

label %>% 
  label_print(mode = "c"
              , filename = "Quinoa-osmotic-stress/experimento_quinua"
              , paper = c(21.0, 29.7)
              )
```

```{r}
label %>% 
  label_print(
    mode = "c",
    filename = "experimento_quinua.pdf",
    paper = c(21.0, 29.7)
  )
#FUNCIONA los guarda en documentos si no hay directorio específico
```

```{r}
label %>% 
  label_print(
    mode = "c",
    filename = "D:/PRACTICAS-PREPROFESIONALES/Quinoa-osmotic-stress/experimento_quinua/labels-copia.pdf",
    paper = c(21.0, 29.7)
  )
```

